#!/bin/bash

cd /data
git clone -b 1.X https://github.com/piwik/piwik.git
chown -R www-data:www-data piwik

mkdir /data/mysql
chown -R mysql:mysql /data/mysql
mv /var/lib/mysql/* /data/mysql
/usr/bin/mysqld_safe &
sleep 5
mysql < /etc/mysql/base.sql

